name: CI Pipline

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with: 
          node-version: 24.14.1

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Tests
        run: npm test
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
              ghcr.io/goku144/tasks-managet-api:latest
              ghcr.io/goku144/tasks-managet-api:prod