name: CI Pipline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  log-start-event:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 24.14.1

      - name: Install Dependencies
        run: npm ci
      
      - name: Run Tests
        run: npm test      
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: demo     # Artifact name
          path: dist 